name: Terraform Destroy

on:
  workflow_dispatch: # Manual trigger only
jobs:
   # First job: Terraform Destroysdf
  terraform-destroy:
    uses: az-lz-20-mb/tmp-sha-pip/.github/workflows/destroy-template.yml@main 
    with:
      module_directory: "terraform/modules/management-groups"
      terraform_version: '1.9.2'
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      
