name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: az-lz-20-mb/tmp-sha-pip/.github/workflows/plan-template.yml@main
    with:
      terraform_version: '1.1.0'
      terraform_directory: 'environments/prod'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}