name: Execute Terraform Plan

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    uses: az-lz-20-mb/tmp-sha-pip/.github/workflows/plan-template.yml@main
    with:
      terraform_directory: "terraform/modules/management-groups"
      terraform_version: '1.1.0'
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
