name: Execute Terraform Plan and Apply

on:
  push:
    branches:
      - main

jobs:
  # First job: Terraform Plan
  terraform-plan:
    uses: az-lz-20-mb/tmp-sha-pip/.github/workflows/plan-template.yml@main
    with:
      module_directory: "terraform/modules/management-groups"
      terraform_version: '1.9.2'
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # Second job: Terraform Apply
  terraform-apply:
    needs: terraform-plan  # Ensures that apply only runs after plan succeeds
    uses: az-lz-20-mb/tmp-sha-pip/.github/workflows/apply-template.yml@main
    with:
      module_directory: "terraform/modules/management-groups"
      terraform_version: '1.9.2'
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      