name: Update GitHub Secret

on:
  workflow_dispatch:

jobs:
  debug-github-token:
    runs-on: ubuntu-latest
    steps:
      - name: Check API Access for GITHUB_TOKEN
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key"
