name: Update GitHub Secret

on:
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install -y gh

      - name: Generate New Secret Value
        id: generate_secret
        run: echo "SECRET_VALUE=$(openssl rand -hex 12)" >> $GITHUB_ENV

      - name: Add Secret to Repository
        run: echo -n "${{ env.SECRET_VALUE }}" | gh secret set MY_SECRET_NAME --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ Teraz powinno działać!
