name: Terraform Unlock

on:
  workflow_dispatch: # Manual trigger only

jobs:
  terraform-unlock:
    name: 'Unlock Terraform State'
    uses: az-lz-20-mb/tmp-sha-pip/.github/workflows/unlock-template.yml@main
    with:
      module_directory: "terraform/modules/management-groups"
      terraform_version: '1.9.2'
      lock_id: "b53e81c5-f3e3-40e5-8eae-909e400bf2d9" # This should be provided when calling the workflow
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
