name: Terraform Unlock

on:
  workflow_dispatch:
    inputs:
      lock_id:
        description: "Enter Terraform Lock ID"
        required: true
        type: string

jobs:
  terraform-unlock:
    name: 'Unlock Terraform State'
    uses: az-lz-20-mb/tmp-sha-pip/.github/workflows/unlock-template.yml@main
    with:
      module_directory: "terraform/modules/management-groups"
      terraform_version: '1.9.2'
      lock_id: "${{ inputs.lock_id }}" # Pobiera wartość wpisaną przez użytkownika
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
